package hello;

import com.aspectran.core.activity.Translet;
import com.aspectran.core.util.logging.Log;
import com.aspectran.core.util.logging.LogFactory;

public class SimplestAction {
	
	private final Log log = LogFactory.getLog(SimplestAction.class);

	public String helloWorld(Translet translet) {
		String msg = "Hello, World.-1";
		
		log.info("The message generated by my first aciton is: " + msg);
		log.info("activityDataMap " + translet.getActivityDataMap(true));

		return msg;
	}

}
